### ISSUE TITLE
The plug-in is successfully installed. The page indicating that the configuration is abnormal is displayed

### ISSUE THREAD

**Issue by chinatochen** [gtt-project/redmine_gtt_assistant#8] opened 2024-01-20 23:39 UTC
**Problem**

**To Reproduce**

**Expectation**

**Screenshots**

![image](https://github.com/gtt-project/redmine_gtt_assistant/assets/43564507/ce3616b0-55e7-4b7d-b108-ec0babc92c66)

errorlog
![image](https://github.com/gtt-project/redmine_gtt_assistant/assets/43564507/6e86d081-6d6f-446c-898b-3d593242ea49)

**Platform/smartphone:**

![image](https://github.com/gtt-project/redmine_gtt_assistant/assets/43564507/cb3918a9-57a2-4886-bcae-500fefc1db74)

**Comment by dkastl** [comment] 2024-01-21 09:04
Have you set the environment variables when starting the Redmine server?

**Comment by dkastl** [comment] 2024-02-07 02:57
I can't reproduce this error, so closing this until more details are available.

**Closed as completed by dkastl** 2024-02-07 02:57 UTC
